# Generated by Django 3.0.2 on 2020-01-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('owner', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
